!results branch beam model
!================================
!-----write displacements and fsum
!
*cfopen,%br_num%_beam_dis00%lo_ad%,txt
 *vwrite,sequ,displ(1,1),displ(1,2),displ(1,3),displ(1,4),displ(1,5),displ(1,6),displ(1,7),displ(1,8),displ(1,9),
 (F5.0,' ',F,' ',F,' ',F,' ',F,' ',F,' ',F,' ',F,' ',F,' ',F) 
*cfclose
!
*cfopen,%br_num%_beamf_sum00%lo_ad%,txt
 *vwrite,sequ,F_SUM(1,1),F_SUM(1,2),F_SUM(1,3),F_SUM(1,4),
  (F5.0,' ',F,' ',F,' ',F,' ',F)  
*cfclose
